# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1in9MS0vh7-9lBrMb8TvGB8hEbBdAk0BS
"""

import pandas as pd

basics = pd.read_csv("title.basics.tsv.gz", sep="\t", na_values="\\N",
                     usecols=["tconst","titleType","startYear","genres"])
principals = pd.read_csv("title.principals.tsv.gz", sep="\t", na_values="\\N",
                         usecols=["tconst","nconst","category"])

# Filter movies, actors, years
basics = basics[(basics["titleType"] == "movie") &
                (basics["startYear"].astype(float) >= 2000)]
principals = principals[principals["category"].isin(["actor","actress"])]

merged = principals.merge(basics, on="tconst")

# Explode multi-genre strings and pivot
merged["genre"] = merged["genres"].str.split(",")
merged = merged.explode("genre")

actor_genre_matrix = merged.groupby(["nconst","genre"]).size().unstack(fill_value=0)

from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd

df = pd.read_csv("imdb_movies_2000to2022_actorXgenre.csv", index_col=0)
df = df.loc[:, df.columns.str.strip() != ""]

queries = ["nm0000233", "nm0000105", "nm0001104"]

sim_matrix = cosine_similarity(df)
sim_df = pd.DataFrame(sim_matrix, index=df.index, columns=df.index)

for query in queries:
    print(f"\nTop 10 most similar to {query}:")
    top10 = sim_df[query].drop(query).nlargest(10)
    print(top10)